import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
  SidebarProvider,
} from './_components/_ui/sidebar'
import { AppSidebar } from '@/components/Sidebar/AppSidebar'
import { Toaster } from 'sonner'
import { AppHeader } from './_components/AppHeader'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position='top-right' />
        <SidebarProvider>
          <AppSidebar />
          <div className='flex flex-col w-full h-full min-h-screen'>
            <AppHeader />
            <main className='flex-1 p-6 w-full'>{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
